

# Source: airflow/templates/worker/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-airflow-worker
  labels:
    app.kubernetes.io/name: airflow
    helm.sh/chart: airflow-10.3.2
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: airflow
      app.kubernetes.io/instance: app-aflow
      app.kubernetes.io/component: worker
  serviceName: app-aflow-airflow-worker-headless
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      annotations:
        checksum/configmap: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      labels:
        app.kubernetes.io/name: airflow
        helm.sh/chart: airflow-10.3.2
        app.kubernetes.io/instance: app-aflow
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: worker
    spec:

      priorityClassName: ""
#      securityContext:
#        fsGroup: 1001
      serviceAccountName: default
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: airflow
                    app.kubernetes.io/instance: app-aflow
                    app.kubernetes.io/component: worker
                namespaces:
                  - "ml-workshop"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      initContainers:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: git-sync
          command:
            - /git-sync
          env:
            - name: GIT_SYNC_REPO
              value: 'https://github.com/masoodfaisal/dags/'
            - name: GIT_SYNC_DEST
              value: gitdags
            - name: GIT_SYNC_BRANCH
              value: main
            - name: GIT_SYNC_ROOT
              value: /tmp/git
            - name: GIT_SYNC_ONE_TIME
              value: 'false'
            - name: GIT_SYNC_REV
            - name: HOME
              value: /tmp
          ports:
            - name: gitsync
              protocol: TCP
              containerPort: 2020
          imagePullPolicy: Always
          volumeMounts:
            - name: dags-data
              mountPath: /tmp/git
          terminationMessagePolicy: File
          image: 'k8s.gcr.io/git-sync/git-sync:v3.2.2'
        - name: airflow-worker
          image: quay.io/ml-aml-workshop/airflow-custom:2.0.0.worker
          imagePullPolicy: "Always"
          # securityContext:
          #   runAsUser: 1001
          resources:
            limits: {}
            requests: {}
          env:
            - name: AIRFLOW_FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-aflow-airflow
                  key: airflow-fernetKey
            - name: AIRFLOW_LOAD_EXAMPLES
              value: "no"
            - name: AIRFLOW_DATABASE_NAME
              value: "bitnami_airflow"
            - name: AIRFLOW_DATABASE_USERNAME
              value: "bn_airflow"
            - name: AIRFLOW_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-aflow-postgresql
                  key: postgresql-password
            - name: AIRFLOW_DATABASE_HOST
              value: "app-aflow-postgresql"
            - name: AIRFLOW_DATABASE_PORT_NUMBER
              value: "5432"

            - name: REDIS_HOST
              value: "app-aflow-redis-master"
            - name: REDIS_PORT_NUMBER
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-aflow-redis
                  key: redis-password
            - name: AIRFLOW_EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW_WEBSERVER_HOST
              value: app-aflow-airflow
            - name: AIRFLOW_WEBSERVER_PORT_NUMBER
              value: "8080"
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: "IKnowWhatYouDidLastYear"

          envFrom:
          ports:
            - name: worker
              containerPort: 8793
          livenessProbe:
            tcpSocket:
              port: worker

            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: worker

            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: dags-data
              mountPath: /opt/bitnami/airflow/dags

      volumes:
        - name: dags-data
          emptyDir: { }

